site_name: GitCells Documentation
site_description: Complete user guide for GitCells - Excel and Git integration
site_url: https://gitcells.com/docs

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - offline

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Basic Concepts: getting-started/concepts.md
  - User Guides:
    - Converting Files: guides/converting.md
    - Tracking Changes: guides/tracking.md
    - Team Collaboration: guides/collaboration.md
    - Resolving Conflicts: guides/conflicts.md
    - Auto-sync Setup: guides/auto-sync.md
    - Common Use Cases: guides/use-cases.md
  - Reference:
    - Commands: reference/commands.md
    - Configuration: reference/configuration.md
    - JSON Format: reference/json-format.md
    - Troubleshooting: reference/troubleshooting.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/gitcells
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

copyright: Copyright &copy; 2024 GitCells