site_name: GitCells Documentation
site_description: Complete user guide for GitCells - Excel and Git integration
site_url: https://classic-homes.github.io/gitcells/
repo_url: https://github.com/Classic-Homes/gitcells
repo_name: Classic-Homes/gitcells

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Basic Concepts: getting-started/concepts.md
  - User Guide:
      - Configuration: user-guide/configuration.md
      - File Watching: user-guide/watching.md
      - Converting Files: user-guide/converting.md
      - Git Integration: user-guide/git-integration.md
      - Terminal UI: user-guide/tui.md
      - Troubleshooting: user-guide/troubleshooting.md
  - Reference:
      - Commands: reference/commands.md
      - Configuration Reference: reference/configuration.md
      - JSON Format: reference/json-format.md
      - API Reference: reference/api.md
  - Development:
      - Architecture: development/architecture.md
      - Contributing: development/contributing.md
      - Building from Source: development/building.md
      - Testing: development/testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Classic-Homes/gitcells
  javascript:
    - https://unpkg.com/mermaid@10/dist/mermaid.min.js
    - https://unpkg.com/mermaid@10/dist/mermaid.esm.min.mjs

copyright: Copyright &copy; 2025 Classic Homes
