name: Bug Report
description: File a bug report to help us improve GitCells
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - chrisloidolt

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: GitCells Version
      description: What version of GitCells are you running?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using? (run `go version`)
      placeholder: "go version go1.21.0 darwin/amd64"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Open file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output or error messages.
      render: shell

  - type: textarea
    id: excel-file
    attributes:
      label: Excel File Details
      description: If the issue is related to a specific Excel file, please describe its characteristics (size, number of sheets, formulas, etc.). DO NOT upload sensitive data.
      placeholder: |
        - File size: ~5MB
        - Number of sheets: 3
        - Contains formulas: Yes
        - Contains merged cells: Yes
        - Excel version: 365

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: search
    attributes:
      label: Existing Issues
      description: Please confirm you have searched for similar issues
      options:
        - label: I have searched for similar issues and found none
          required: true