name: Documentation

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'requirements.txt'
  workflow_dispatch:

concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build-and-validate:
    name: Build and Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install MkDocs and dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build documentation
      run: mkdocs build --strict --verbose
      
    - name: Check for broken links (PR only)
      if: github.event_name == 'pull_request'
      run: |
        pip install linkchecker
        mkdocs serve &
        SERVER_PID=$!
        sleep 5
        linkchecker http://localhost:8000 --no-warnings --ignore-url=github.com
        kill $SERVER_PID
      continue-on-error: true
      
    - name: Upload build artifacts (on failure)
      uses: actions/upload-artifact@v4
      if: failure() && github.event_name == 'pull_request'
      with:
        name: docs-build-output
        path: site/
        retention-days: 7
        
    - name: Upload pages artifact (main branch only)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site
        
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-validate
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4